C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseShapeShader.vert -o BaseShapeShader.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseTextShader.vert -o BaseTextShader.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseShapeShader_Instance.vert -o BaseShapeShader_Instance.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseShapeShader_Texture_Instance.vert -o BaseShapeShader_Texture_Instance.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseTextShader_Instance.vert -o BaseTextShader_Instance.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseShapeShader_Color.frag -o BaseShapeShader_Color.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseShapeShader_Texture.frag -o BaseShapeShader_Texture.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseTextShader_Frag.frag -o BaseTextShader_Frag.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseShapeShader_Color_Instance.frag -o BaseShapeShader_Color_Instance.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseShapeShader_Texture_Instance_Frag.frag -o BaseShapeShader_Texture_Instance_Frag.spv
C:\VulkanSDK\1.2.154.1/Bin32/glslc.exe BaseTextShader_Instance_Frag.frag -o BaseTextShader_Instance_Frag.spv